# Generated by Django 4.2.30 on 2026-08-11 07:51

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.manager
import django_ltree.fields


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="taxonomy",
            managers=[
                ("t_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="path",
            field=django_ltree.fields.PathField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["path"], name="taxonomy_ta_path_98acbc_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="taxonomy",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["path"], name="taxonomy_ta_path_85a7ea_gist"
            ),
        ),
    ]
