# Generated by Django 4.2.30 on 2026-08-11 08:00

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.manager
import django_ltree.fields


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0002_alter_taxonomy_managers_alter_taxonomy_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxonomyName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    django_ltree.fields.PathField(blank=True, null=True, unique=True),
                ),
                ("name", models.TextField()),
            ],
            options={
                "ordering": ("path",),
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["path"], name="taxonomy_ta_path_b7bdee_btree"
                    ),
                    django.contrib.postgres.indexes.GistIndex(
                        fields=["path"], name="taxonomy_ta_path_59d4f7_gist"
                    ),
                ],
            },
            managers=[
                ("t_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
