name: Publish to PYPI

on:
    release:
        types: [published]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
            - name: Install python dependencies
              run: |
                  poetry install --sync --no-interaction --no-root --with test
                  poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

            # - name: Test
            #   run: |
            #       poetry run pytest .
            - name: Publish
              run: |
                  poetry publish --build
